services:
  example:
    build:
      target: example
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:latest
    command: ["postgres", "-c", "log_min_messages=FATAL"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    restart: always
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql
        tmpfs:
          mode: 01777
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 1s
      retries: 10
